function [controlPort, dataPort, configFileName, loadConfig] = configDialog()

comPortChoice = {'COM1',  'COM2',  'COM3',  'COM4',  'COM5',  'COM6',  'COM7',  'COM8',  'COM9', 'COM10',...
    'COM11', 'COM12', 'COM13', 'COM14', 'COM15', 'COM16', 'COM17', 'COM18', 'COM19','COM20',...
    'COM21', 'COM22', 'COM23', 'COM24', 'COM25', 'COM26', 'COM27', 'COM28', 'COM29','COM30',...
    'COM31', 'COM32', 'COM33', 'COM34', 'COM35', 'COM36', 'COM37', 'COM38', 'COM39','COM40',...
    'COM41', 'COM42', 'COM43', 'COM44', 'COM45', 'COM46', 'COM47', 'COM48', 'COM49','COM50',...
    'COM51', 'COM52', 'COM53', 'COM54', 'COM55', 'COM56', 'COM57', 'COM58', 'COM59','COM60',...
    'COM61', 'COM62', 'COM63', 'COM64', 'COM65', 'COM66', 'COM67', 'COM68', 'COM69','COM70',...
    'COM71', 'COM72', 'COM73', 'COM74', 'COM75', 'COM76', 'COM77', 'COM78', 'COM79','COM80',...
    'COM81', 'COM82', 'COM83', 'COM84', 'COM85', 'COM86', 'COM87', 'COM88', 'COM89','COM90',...
    'COM91', 'COM92', 'COM93', 'COM94', 'COM95', 'COM96', 'COM97', 'COM98', 'COM99','COM100',...
    };
configPathName = '..\chirp_configs';
configFileName = 'pc_6843_3d_aop_overhead_3m_radial.cfg';

%Find COM port numbers (only valid for 2019b and later)
% [controlPortNum, dataPortNum] = findDemoComPorts();
% if isempty(controlPortNum) || isempty(dataPortNum)
%     controlPortNum = 3;
%     dataPortNum = 4;
% end

% Control port selection
hDialog = dialog('Position',[300 300 360 260],'Name','Configuration');
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 210 100 40],...
    'HorizontalAlignment','left',...
    'String','Select control port:');

popup_control = uicontrol('Parent',hDialog,...
    'Style','popupmenu',...
    'Position',[20 200 100 30],...
    'String',comPortChoice,...
    'Value', 11); %controlPortNum); %auto com ports only with 2019b and later

% Data port selection
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[140 210 100 40],...
    'HorizontalAlignment','left',...
    'String','Select data port:');

popup_data = uicontrol('Parent',hDialog,...
    'Style','popupmenu',...
    'Position',[140 200 100 30],...
    'String', comPortChoice,...
    'Value', 12); %dataPortNum); %auto com ports only with 2019b and later

% Chirp configuration selection
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 80 200 40],...
    'HorizontalAlignment','left',...
    'String','Select chirp configuration file:');

hFileName = uicontrol('Parent', hDialog,...
    'Style','text',...
    'Position',[20 60 260 40],...
    'HorizontalAlignment','left',...
    'String', configFileName);

hFileSelect = uicontrol('Parent',hDialog,...
    'Style', 'pushbutton',...
    'Position',[280 85 60 20],...
    'String','Browse',...
    'Callback',@configFileSelect_callback);

setappdata(hFileSelect,'configFileName', [configPathName,'\', configFileName]);

% Load configuration selection
hLoadConfig = uicontrol('Parent',hDialog,...
    'Style','Radio',...
    'String','Load Configuration',...
    'Position',[20 20 160 20],...
    'Value',0);

% Extract the outputs
uicontrol('Parent',hDialog,...
    'Position',[200 20 60 20],...
    'String','Done',...
    'Callback',@done_callback);

% Wait for d to close before running to completion
uiwait(hDialog);

    function [pathname, filename] = configFileSelect_callback (source, ~)
    [filename, pathname] = uigetfile({'*.cfg'},...
        'Select Chirp configuration File', ...
        getappdata(source, 'configFileName'));
    hFileName.String = filename;
    setappdata(source, 'configFileName', [pathname, filename]);
    end
    
    function done_callback (~, ~)
        controlPort = popup_control.Value;
        dataPort = popup_data.Value;
        loadConfig = hLoadConfig.Value;
        configFileName = getappdata(hFileSelect, 'configFileName');
        delete(gcf);
    end
end

%Find COM port numbers for control and data serial ports
function [controlPortNum, dataPortNum] = findDemoComPorts()
    comPortsAvailable = serialportlist("available");
    numPortsAvailable = length(comPortsAvailable);
    
    if numPortsAvailable>=2
        % Assuming the first available port is Control and the second
        % available port is Data. The user can switch if needed
        controlPortNum  = str2double(strtok(comPortsAvailable(1),'COM'));
        dataPortNum     = str2double(strtok(comPortsAvailable(2),'COM'));
    else
        controlPortNum = [];
        dataPortNum = [];
    end
  
end
